version: '3.8'

services:
  app:
    build: .
    container_name: qr-app
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    networks:
      - web

networks:
  web:
    name: traefik-network
    external: false
