version: '3.8'

services:
  app:
    build: .
    container_name: qr-app
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
    ports:
      - "${HTTP_PORT:-80}:${PORT:-3000}"
    networks:
      - qr-network

networks:
  qr-network:
    name: qr-network
    external: false